# Generated by Django 2.1.7 on 2019-10-01 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IpAddress', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.CharField(max_length=100)),
                ('download', models.CharField(max_length=100)),
                ('ping_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Data')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60)),
                ('user_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Data')),
            ],
        ),
    ]
